// <auto-generated />
using System;
using GS1.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GS1.Infrastructure.Migrations
{
    [DbContext(typeof(GS1DbContext))]
    [Migration("20260130113329_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GS1.Core.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GLN")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nchar(13)")
                        .IsFixedLength();

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyName")
                        .HasDatabaseName("IX_Customers_CompanyName");

                    b.HasIndex("GLN")
                        .IsUnique()
                        .HasDatabaseName("IX_Customers_GLN");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("GS1.Core.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GTIN")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("IX_Products_CustomerId");

                    b.HasIndex("GTIN")
                        .IsUnique()
                        .HasDatabaseName("IX_Products_GTIN");

                    b.HasIndex("ProductName")
                        .HasDatabaseName("IX_Products_ProductName");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("GS1.Core.Entities.SSCC", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GS1DataMatrix")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ParentSSCCId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SSCCCode")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nchar(18)")
                        .IsFixedLength();

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ParentSSCCId")
                        .HasDatabaseName("IX_SSCCs_ParentSSCCId");

                    b.HasIndex("SSCCCode")
                        .IsUnique()
                        .HasDatabaseName("IX_SSCCs_SSCCCode");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_SSCCs_Type");

                    b.HasIndex("WorkOrderId")
                        .HasDatabaseName("IX_SSCCs_WorkOrderId");

                    b.ToTable("SSCCs", (string)null);
                });

            modelBuilder.Entity("GS1.Core.Entities.SerialNumber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GS1DataMatrix")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PrintedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("SSCCId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Serial")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SSCCId")
                        .HasDatabaseName("IX_SerialNumbers_SSCCId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_SerialNumbers_Status");

                    b.HasIndex("WorkOrderId")
                        .HasDatabaseName("IX_SerialNumbers_WorkOrderId");

                    b.HasIndex("WorkOrderId", "Serial")
                        .IsUnique()
                        .HasDatabaseName("IX_SerialNumbers_WorkOrderId_Serial");

                    b.ToTable("SerialNumbers", (string)null);
                });

            modelBuilder.Entity("GS1.Core.Entities.WorkOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("BoxesPerPallet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(100);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ItemsPerBox")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10);

                    b.Property<long>("LastSerialNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProductionQuantity")
                        .HasColumnType("int");

                    b.Property<long>("SerialNumberStart")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("WorkOrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("BatchNumber")
                        .HasDatabaseName("IX_WorkOrders_BatchNumber");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_WorkOrders_ProductId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_WorkOrders_Status");

                    b.HasIndex("WorkOrderNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_WorkOrders_WorkOrderNumber");

                    b.ToTable("WorkOrders", (string)null);
                });

            modelBuilder.Entity("GS1.Core.Entities.Product", b =>
                {
                    b.HasOne("GS1.Core.Entities.Customer", "Customer")
                        .WithMany("Products")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("GS1.Core.Entities.SSCC", b =>
                {
                    b.HasOne("GS1.Core.Entities.SSCC", "ParentSSCC")
                        .WithMany("ChildSSCCs")
                        .HasForeignKey("ParentSSCCId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("GS1.Core.Entities.WorkOrder", "WorkOrder")
                        .WithMany("SSCCs")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParentSSCC");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("GS1.Core.Entities.SerialNumber", b =>
                {
                    b.HasOne("GS1.Core.Entities.SSCC", "SSCC")
                        .WithMany("SerialNumbers")
                        .HasForeignKey("SSCCId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GS1.Core.Entities.WorkOrder", "WorkOrder")
                        .WithMany("SerialNumbers")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SSCC");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("GS1.Core.Entities.WorkOrder", b =>
                {
                    b.HasOne("GS1.Core.Entities.Product", "Product")
                        .WithMany("WorkOrders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("GS1.Core.Entities.Customer", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("GS1.Core.Entities.Product", b =>
                {
                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("GS1.Core.Entities.SSCC", b =>
                {
                    b.Navigation("ChildSSCCs");

                    b.Navigation("SerialNumbers");
                });

            modelBuilder.Entity("GS1.Core.Entities.WorkOrder", b =>
                {
                    b.Navigation("SSCCs");

                    b.Navigation("SerialNumbers");
                });
#pragma warning restore 612, 618
        }
    }
}
